FROM alpine:latest

RUN apk --no-cache add curl
RUN adduser -s /bin/bash -D pocketbase

USER pocketbase

WORKDIR /home/pocketbase
RUN curl -LJ https://github.com/pocketbase/pocketbase/releases/download/v0.17.5/pocketbase_0.17.5_linux_arm64.zip -o pb.zip
RUN unzip pb
RUN rm pb.zip

ENV PRIVATE_POCKETBASE_ADMIN=""
ENV PRIVATE_POCKETBASE_PASSWORD=""
RUN mkdir pb_migrations
RUN mkdir pb_hooks
EXPOSE 8090
VOLUME [ "/home/pocketbase/pb_data" ]

COPY --chown=pocketbase --chmod=700 ./dockerfiles/pocketbase/entrypoint.sh .
COPY --chown=pocketbase --chmod=700 ./pb_migrations/ ./pb_migrations
COPY --chown=pocketbase --chmod=700 ./pb_hooks/ ./pb_hooks
ENTRYPOINT [ "./entrypoint.sh" ]