FROM node:20-alpine

USER node

WORKDIR /home/node

COPY package.json ./
RUN npm install --ci
COPY ./build .


ENV PUBLIC_POCKETBASE_URL=""
ENV PRIVATE_POCKETBASE_URL=""
ENV ORIGIN="http://localhost:3000"
ENV PRIVATE_POCKETBASE_ADMIN=""
ENV PRIVATE_POCKETBASE_PASSWORD=""

EXPOSE 3000

CMD ["node","index.js"]