name: Create open-ticket docker container
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  create_docker_container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: save build folder
      - name: Display structure of downloaded files
        run: ls -R
        # - name: Checkout
        #   uses: actions/checkout@v3
        # - name: Set up QEMU
        #   uses: docker/setup-qemu-action@v2
        # - name: Set up Docker Buildx
        #   id: buildx
        #   uses: docker/setup-buildx-action@v2
        # - name: Login to Docker Hub
        #   uses: docker/login-action@v2
        #   with:
        #     username: ${{ secrets.DOCKERHUB_USERNAME }}
        #     password: ${{ secrets.DOCKERHUB_TOKEN }}
        # - name: Build and push
        #   uses: docker/build-push-action@v4
        #   with:
        #     context: .
        #     platforms: linux/amd64,linux/arm/v7
        #     push: ${{ github.event_name != 'pull_request' }}
        #     tags: ${{ steps.<meta_id>.outputs.tags }}
        #     labels: ${{ steps.<meta_id>.outputs.labels }}
